export enum BreadcrumbAcoesEnum {
  Cancelar = 'cancelar',
  Criar = 'criar',
  Editar = 'editar',
  Visualizar = 'visualizar',
  Salvar = 'salvar',
  Enviar = 'enviar',
  Prospectar = 'prospectar',
  AssinarAutuar = 'autuarEdocs',
  Voltar = 'voltar',
  Revisar = 'revisar',
  Arquivar = 'arquivar',
  Complementar = 'complementar',
  EnviarPedindoParecerEstrategicoOrcamentario = 'parecerestrategicoorcamentario',
  EnviarEfetivacaoParecerEstrategicoOrgamentario = 'efetivarparecerestrategicoorcamentario',
  EntranharPareceresProcessoEdocs = 'entranharPareceresProcessoEdocs',
  EntranharParecerGEOCdocs = 'entranharParecerGEOCdocs',
  CapturarparecerGEOC = 'capturarparecerGEOC',
  Exportar = 'exportar',
  SolicitarAutorizacao = 'solicitarAutorizacao',
  Autuar = 'autuar',
}

export enum BreadcrumbContextoEnum {
  Projetos = 'projetos',
  Programas = 'programas',
  CartasConsulta = 'cartasconsulta',
  Prospeccao = 'prospeccao',
  Organizacoes = 'organizacoes',
  Pessoas = 'pessoas',
}
