/**
 * Catálogo de textos da interface em português (pt-BR).
 * Reutilize uma chave existente antes de criar outra. Dados do usuário e mensagens
 * recebidas da API permanecem dinâmicos. Use parâmetros para textos variáveis.
 * As chaves são estáveis: traduções futuras devem manter os mesmos identificadores.
 */
const MENSAGENS_PT_BR = {
  A_AUTUACAO_DO_PROGRAMA_FOI_SOLICITADA: "A Autuação do Programa foi solicitada!",
  A_AUTUACAO_FOI_REALIZADA_COM_SUCESSO: "A Autuação foi realizada com sucesso!",
  A_LISTA_DE_ASSINANTES_NAO_EXISTE_OU_ESTA_VAZIA_E_NECESSARIO_SOLICITAR_AS_AUTORIZACOES_PRIMEIRO: "A lista de assinantes não existe ou está vazia! É necessário solicitar as Autorizações primeiro.",
  A_PESSOA_JA_ESTA_CADASTRADA_COMO_RESPONSAVEL_DA_ORGANIZACAO: "A pessoa já está cadastrada como responsável da organização:",
  ABR: "Abr",
  ABRIL: "Abril",
  ABRIR_FILTROS: "Abrir filtros",
  ACAO: 'Ação',
  ACAO_NAO_POSSUI_ORCAMENTO_DEFINIDO_NA_LOA: "Ação não possui orçamento definido na LOA",
  ACAO_PRINCIPAL: "Ação Principal",
  ACAO_REMOVIDA_DO_PROJETO: "Ação removida do projeto.",
  ACAO_VALOR: "Ação #{p0}",
  ACOES: "Ações",
  ACOES_DO_PLANEJAMENTO: "Ações do planejamento",
  ACOES_DO_PROJETO: "Ações do Projeto",
  ADICIONANDO_INDICADOR_PROJETO: "Adicionando indicador projeto...",
  ADICIONAR: "Adicionar",
  ADICIONAR_2: "+ Adicionar",
  ADICIONAR_NOVA_ACAO: "Adicionar Nova Ação",
  ADICIONAR_NOVO_INDICADOR: "Adicionar Novo Indicador",
  AFEGAO: "Afegão",
  AGO: "Ago",
  AGOSTO: "Agosto",
  AGUARDANDO_ASSINATURAS: "Aguardando Assinaturas",
  AGUARDANDO_E_DOCS: "Aguardando E-Docs",
  ALEMAO: "Alemão",
  ALGUM_MEMBRO_DA_EQUIPE_NAO_POSSUI_UM_PAPEL_ATRIBUIDO: "Algum membro da equipe não possui um papel atribuído",
  ALINHAMENTO: "Alinhamento",
  ALTERAR: "Alterar",
  ALTERAR_AS_ORGANIZACOES_A_QUAL_ESTA_PESSOA_PERTENCE_IRA_DESVINCULA_LA_COMO_RESPONSAVEL_DA_ORGANIZACAO_ACIMA: "Alterar as organizações a qual esta pessoa pertence irá desvincula-la como responsável da organização acima!",
  AMERICANO: "Americano",
  ANEXAR_PARECER_EM_PDF: "Anexar parecer em PDF",
  ANGOLANO: "Angolano",
  ANO: "Ano",
  ANO_2: "ANO",
  ANTERIOR: "Anterior",
  ANTIGUANO: "Antiguano",
  APONTAR_O_RESULTADO_ESPECIFICO_E_DETERMINADO_A_SER_ALCANCADO_CUJA_IMPLEMENTACAO_SERA_MEDIDA_POR_MEIO_DO_INDICA: "Apontar o resultado específico e determinado a ser alcançado, cuja implementação será medida por meio do indicador. A meta deverá estar relacionada aos objetivos e aos resultados esperados e sua consecução relacionada ao tempo de implantação do projeto.",
  APRESENTAR_PROJECAO_DAS_TAXAS_QUE_PODERAO_COMPOR_EVENTUAL_OPERACAO_DE_CREDITO_CONSIDERANDO_CONTRATOS_FIRMADOS: "Apresentar projeção das taxas que poderão compor eventual operação de crédito, considerando contratos firmados e a experiência prévia com bancos de fomento.",
  ARABE_EMIRATENSE: "Árabe, emiratense",
  AREAS_DE_ATUACAO: "Áreas de Atuação",
  AREAS_DE_ATUACAO_2: "-- Áreas de Atuação --",
  ARGELIA: "Argélia",
  ARGENTINO: "Argentino",
  ARMENO: "Armeno",
  ARQUIVAMENTO_ERRO_DETALHE: 'Erro ao enviar aviso de arquivamento: {erro}',
  ARQUIVAR: "Arquivar",
  ARRANJO_INSTITUCIONAL: "Arranjo Institucional",
  ARRANJOS_INSTITUCIONAIS: "Arranjos Institucionais",
  AS: "às",
  AS_ACOES_DO_PLANEJAMENTO_SERAO_OCULTADAS_E_PODERAO_SER_RESTAURADAS_AO_DESMARCAR_ESTA_OPCAO: "As ações do planejamento serão ocultadas e poderão ser restauradas ao desmarcar esta opção.",
  AS_AUTORIZACOES_FORAM_ENVIADAS_COM_SUCESSO: "As Autorizações foram enviadas com sucesso!",
  AS_AUTORIZACOES_FORAM_SOLICITADAS: "As Autorizações foram solicitadas!",
  ASSINADO: "Assinado",
  ASSINADO_COM_SUCESSO: "Assinado com sucesso!",
  ASSINANDO: "Assinando",
  ASSINANTES: "Assinantes",
  ASSINAR: "Assinar",
  ASSINAR_E_AUTUAR: "Assinar e Autuar",
  ASSINAR_E_CAPTURAR_PARECER: "Assinar e Capturar Parecer",
  ASSINATURA_CONFIRMADA: "Assinatura confirmada",
  ASSINATURA_E_CAPTURA_DO_DIC_DOCUMENTO_INICIAL_DE_CAPTACAO_GERADO_EM_PDF_COM_OS_DADOS_DO_FORMULARIO: "Assinatura e captura do DIC (Documento Inicial de Captação), gerado em PDF com os dados do formulário;",
  ASSINATURA_E_CAPTURA_DO_PARECER_GERADO_EM_PDF_A_PARTIR_DOS_DADOS_INFORMADOS_NESTE_FORMULARIO: "Assinatura e captura do parecer, gerado em PDF a partir dos dados informados neste formulário;",
  ASSINATURA_E_CAPTURA_FINALIZADAS_COM_SUCESSO: "ASSINATURA E CAPTURA FINALIZADAS COM SUCESSO!",
  ASSINATURA_FOI_ENVIADA_COM_SUCESSO: "Assinatura foi enviada com sucesso",
  ASSINATURAS: "Assinaturas",
  ASSINATURAS_SOLICITADAS: "Assinaturas Solicitadas",
  ATE_VALOR: " Até: {p0} ",
  ATENCAO: "Atenção!",
  AUMENTAR_O_ZOOM: "Aumentar o zoom",
  AUSTRALIANO: "Australiano",
  AUSTRIACO: "Austríaco",
  AUTORIZACOES_DO_PROGRAMA: "Autorizações do Programa",
  AUTORIZACOES_PROGRAMA: "Autorizações Programa",
  AUTORIZO_A_ASSINATURA_ELETRONICA_DO_PROGRAMA_VALOR_DESTINADO_A_PROSPECCAO_DE_RECURSOS_CONFORME_DOCUMENTO_APRES: " Autorizo a assinatura eletrônica do Programa \"{p0}\", destinado à prospecção de recursos, conforme documento apresentado nesta tela. Declaro ciência de que a assinatura será realizada por meio do sistema SISCAP, com registro e validade no e-Docs. ",
  AUTUACAO_DE_PROCESSO_DE_SOLICITACAO_DE_CAPTACAO_DE_RECURSOS_PARA_A_SUA_INSTITUICAO: "Autuação de processo de Solicitação de Captação de Recursos para a sua instituição;",
  AUTUADO: "Autuado",
  AUTUAR: "Autuar",
  AUTUAR_O_PROGRAMA: "Autuar o Programa",
  AUTUAR_PROGRAMA_CONFIRMACAO: 'Esta ação realizará a autuação de um processo no E-Docs para o programa de captação {programa}, utilizando a sua identidade {usuario}({lotacao})',
  AVALIAR_A_ADERENCIA_DO_PROJETO_A_CONTRATACOES_JA_REALIZADAS_OU_EM_PROSPECCAO_BEM_COMO_A_VIABILIDADE_DE_ASSOCIA: "Avaliar a aderência do projeto a contratações já realizadas ou em prospecção, bem como a viabilidade de associação com outros projetos para a formatação de uma proposta de programa;",
  AVOCAR: "Avocar",
  BAHAMENSE: "Bahamense",
  BAIXANDO_DIC: "Baixando DIC...",
  BAIXAR_DIC: "Baixar DIC",
  BAIXAR_PARECER: "Baixar parecer",
  BAIXAR_PROGRAMA: "Baixar Programa",
  BANCO_DE_PROJETOS: "Banco de Projetos",
  BANGLADESH: "Bangladesh",
  BARBADIANO_BARBADENSE: "Barbadiano, barbadense",
  BASE_DE_REFERENCIA: "BASE DE REFERÊNCIA",
  BASE_DE_REFERENCIA_2: "BASE DE REFERÊNCIA:",
  BECHUANO: "Bechuano",
  BELGA: "Belga",
  BELIZENHO: "Belizenho",
  BOLIVIANO: "Boliviano",
  BRASILEIRO: "Brasileiro",
  BRITANICO: "Britânico",
  BUSINESS_INTELLIGENCE: "Business Intelligence",
  CADASTRANDO_DIC: "Cadastrando DIC...",
  CADASTRAR_CARTA_CONSULTA: "Cadastrar Carta Consulta",
  CADASTRAR_ORGANIZACAO: "Cadastrar Organização",
  CADASTRAR_PESSOA: "Cadastrar Pessoa",
  CADASTRAR_PROGRAMA: "Cadastrar Programa",
  CADASTRAR_PROJETO: "Cadastrar Projeto",
  CADASTRAR_PROSPECCAO: "Cadastrar Prospecção",
  CAMARONENSE: "Camaronense",
  CAMPO_NAO_ENCONTRADO: "Campo não encontrado:",
  CAMPO_OBRIGATORIO: "Campo obrigatório",
  CAMPO_OBRIGATORIO_2: "Campo obrigatório.",
  CANADENSE: "Canadense",
  CANCELAR: "Cancelar",
  CANCELAR_OPERACAO: "Cancelar operação",
  CAPTACAO: "Captação",
  CAPTACAO_DE_RECURSOS: "Captação de Recursos",
  CARREGANDO: "Carregando...",
  CARREGANDO_ACOES: "Carregando ações...",
  CARREGANDO_ACOES_DO_PLANEJAMENTO: "Carregando ações do planejamento",
  CARREGANDO_ACOES_DO_PLANEJAMENTO_2: "Carregando ações do planejamento...",
  CARREGANDO_INDICADORES: "Carregando indicadores...",
  CARREGANDO_RESPONSAVEIS: "Carregando responsáveis...",
  CARTA_CONSULTA: "Carta Consulta:",
  CARTA_CONSULTA_2: "Carta Consulta",
  CARTA_DE_SOLICITACAO: "Carta de Solicitação",
  CASO_O_ERRO_PERSISTA_CONTATE_O_SUPORTE: "Caso o erro persista, contate o suporte.",
  CHILENO: "Chileno",
  CHINES: "Chinês",
  CIDADE: "Cidade",
  CIDADE_2: "-- Cidade --",
  CINGALES: "Cingalês",
  CLIQUE_EM: "Clique em",
  CLONAR_PROSPECCAO: "Clonar Prospecção",
  CLOSE_2: "Close",
  CNPJ: "CNPJ",
  COLOMBIANO: "Colombiano",
  COMORENSE: "Comorense",
  COMPLEMENTAR: "Complementar",
  CONCLUIR_PARECER: "Concluir Parecer",
  CONCLUSAO: "Conclusão",
  CONFIRMAR: "Confirmar",
  CONFIRMAR_ACAO: "Confirmar ação",
  CONTEUDO: "Conteúdo",
  CONTRATOS: "Contratos",
  COR_DE_FUNDO_DO_TEXTO: "Cor de fundo do texto",
  COR_DO_TEXTO: "Cor do texto",
  CORTAR_IMAGEM: "Cortar Imagem",
  COSTARRIQUENHO: "Costarriquenho",
  CPF_INVALIDO: "CPF inválido",
  CRIADO_EM: "Criado Em",
  CRIAR: "Criar",
  CRIAR_UM_INDICADOR_DE_PROJETO: "CRIAR UM INDICADOR DE PROJETO",
  CRIAR_UM_INDICADOR_DE_PROJETO_2: "+ Criar um Indicador de Projeto",
  CROATA: "Croata",
  CUBANO: "Cubano",
  CUSTOS_ADMINISTRATIVOS: "% Custos Administrativos",
  DASHBOARD: "Dashboard",
  DATA: "Data",
  DD_MM_YYYY_HH_MM_SS: "dd/MM/yyyy HH:mm:ss",
  DE: "De:",
  DECLARAR_A_ELEGIBILIDADE_DA_PROPOSTA_PARA_PLEITO_DE_FINANCIAMENTO: "Declarar a elegibilidade da proposta para pleito de financiamento;",
  DELETAR: "Deletar",
  DESAFIO: "DESAFIO",
  DESAFIOS: "Desafios",
  DESCREVE_A_FORMULA_OU_METODOLOGIA: "Descreve a fórmula ou metodologia.",
  DESCREVER_AS_ACOES_ESCOLHIDAS_PARA_O_ENFRENTAMENTO_OU_SOLUCAO_DO_S_PROBLEMA_S_DESCRITO_S_NO_ITEM_ANTERIOR: "Descrever as ações escolhidas para o enfrentamento ou solução do(s) problema(s) descrito(s) no item anterior.",
  DESCREVER_CADA_INDICADOR_DE_FORMA_ESPECIFICA_E_ESTABELECER_AS_FORMULAS_DE_CALCULO_ADEQUADAS_FAZER_REFERENCIA_A: "Descrever cada indicador de forma específica e estabelecer as fórmulas de cálculo adequadas. Fazer referência aos objetivos específicos pertinentes ao indicador e às áreas estratégicas relacionadas. Empregar preferencialmente o modelo SMART para a definição de indicadores.",
  DESCREVER_O_TIPO_DE_INDICADOR: "Descrever o tipo de indicador.",
  DESCRICAO_DE_ACOES_SECUNDARIAS_E_PRODUTOS: "Descrição de ações secundárias e produtos",
  DESCRICAO_DO_INDICADOR: "Descrição do indicador",
  DESDE_VALOR: " Desde: {p0} ",
  DESEJA_ENVIAR_AS_AREAS_ESTRATEGICA_E_ORCAMENTARIA_PARA_ELABORACAO_DOS_PARECERES: "Deseja enviar às áreas estratégica e orçamentária para elaboração dos pareceres?",
  DESEJA_ENVIAR_O_DIC_PARA_REVISAO: "Deseja enviar o DIC para revisão?",
  DESEJA_FAZER_O_ENVIO_DO_DIC_PARA_O_GESTOR_DO_ORGAO_DE_ORIGEM: "Deseja fazer o envio do DIC para o gestor do orgão de origem?",
  DESEJA_MARCAR_ESTE_PROJETO_COMO_NAO_PREVISTO_NO_PPA: "Deseja marcar este projeto como não previsto no PPA?",
  DESENTRANHAMENTO_DO_DIC_ANTERIOR_DO_PROCESSO: "Desentranhamento do DIC anterior do processo;",
  DESENTRANHAR: "Desentranhar",
  DESPACHAR_PROCESSO: "Despachar Processo",
  DESPACHO_COM_PEDIDO_DE_ANALISE_DO_PROCESSO_A_SUBSECRETARIA_DE_CAPTACAO_DE_RECURSOS_SUBCAP_DA_SECRETARIA_DE_ECO: "Despacho com pedido de análise do processo à Subsecretaria de Captação de Recursos (SUBCAP) da Secretaria de Economia e Planejamento (SEP).",
  DESTINATARIOS: "Destinatários",
  DETALHAMENTO_ORCAMENTARIO_LOA: "Detalhamento Orçamentário LOA",
  DEVERA_REFLETIR_O_QUE_SE_DESEJA_ALCANCAR_COM_AS_ACOES_DO_DIC_ABRANGENDO_A_VISAO_AMPLA_E_O_SEU_PROPOSITO_GERAL: "Deverá refletir o que se deseja alcançar com as ações do DIC, abrangendo a visão ampla e o seu propósito geral. Deve estar explicitamente relacionado aos problemas e necessidades apontados.",
  DEVERAO_CORRESPONDER_AOS_RESULTADOS_QUE_O_DIC_PRETENDE_ATINGIR_CONTRIBUINDO_PARA_O_ALCANCE_DO_OBJETIVO_GERAL_D: "Deverão corresponder aos resultados que o DIC pretende atingir, contribuindo para o alcance do objetivo geral. Deverão ser apresentados de maneira específica, mensurável, atingível e realista e relacionados aos indicadores propostos. Também deverão ter vínculo com os Objetivos de Desenvolvimento Sustentável da ONU.",
  DEZ: "Dez",
  DEZEMBRO: "Dezembro",
  DIC: "DIC",
  DICS_PROPOSTOS: "DICS Propostos",
  DIFERENCA_VALOR: " Diferença: {p0} ",
  DIGITE_A_META: "Digite a meta",
  DIGITE_AQUI_O_TEXTO_DO_PARECER: "Digite aqui o texto do parecer...",
  DIGITE_O_CPF: "Digite o CPF",
  DIGITE_O_NOME: "Digite o nome",
  DINAMARQUES: "Dinamarquês",
  DOCUMENTO_INICIAL_DE_CAPTACAO: "Documento Inicial de Captação",
  DOCUMENTO_INICIAL_DE_CAPTACAO_DIC: "Documento Inicial de Captação (DIC)",
  DOM: "Dom",
  DOMINICANA: "Dominicana",
  DOMINICANO: "Dominicano",
  E_DOCS: "E-Docs",
  E_MAIL_DE_PEDIDO_DE_PARECER_REENVIADO_COM_SUCESSO: "E-mail de pedido de parecer reenviado com sucesso.",
  E_OBRIGATORIO_INFORMAR_AO_MENOS_UM_INDICADOR: "É obrigatório informar ao menos um indicador.",
  E_OBRIGATORIO_PREENCHER_TODAS_AS_METAS_DOS_INDICADORES: "É obrigatório preencher todas as metas dos indicadores.",
  EDICAO: "Edição",
  EDITAR: "Editar",
  EDITAR_CARTA_CONSULTA: "Editar Carta Consulta",
  EDITAR_DIC: "Editar DIC",
  EDITAR_DIC_VIA_LINK: "Editar DIC (via link)",
  EDITAR_DOCUMENTO_INICIAL_DE_CAPTACAO_DIC: "Editar Documento Inicial de Captação - DIC",
  EDITAR_FOTO: "Editar Foto",
  EDITAR_ORGANIZACAO: "Editar Organização",
  EDITAR_PESQUISA_DE_FONTE_DE_FINANCIAMENTO: "Editar Pesquisa de Fonte de Financiamento",
  EDITAR_PESSOA: "Editar Pessoa",
  EDITAR_PROGRAMA: "Editar Programa",
  EDITAR_PROSPECCAO: "Editar Prospecção",
  EGIPCIO: "Egípcio",
  ELABORACAO: "Elaboração",
  EMAIL: "Email",
  EMAIL_INVALIDO: "Email inválido",
  EMBLEMA_SISCAP: "Emblema Siscap",
  ENTENDI: "Entendi",
  ENTRANHAMENTO_DO_DIC_ATUAL_CAPTURADO_AO_PROCESSO: "Entranhamento do DIC atual capturado ao processo;",
  ENTRANHAMENTO_DO_DIC_CAPTURADO_AO_PROCESSO: "Entranhamento do DIC capturado ao processo;",
  ENTRANHAMENTO_DOS_PARECERES_CAPTURADOS_NO_E_DOCS: "Entranhamento dos pareceres capturados no E-Docs;",
  ENTRANHAMENTO_PARECERES_FINALIZADO_COM_SUCESSO: "ENTRANHAMENTO PARECERES FINALIZADO COM SUCESSO!",
  ENTRANHAR_ARQUIVO: "Entranhar Arquivo",
  ENTRANHAR_PARECER: "Entranhar Parecer",
  ENTRANHAR_PARECERES: "Entranhar Pareceres",
  ENTRAR: "Entrar",
  ENVIAR: "Enviar",
  ENVIAR_PARECER: "Enviar Parecer",
  ENVIAREMOS_EMAIL_INFORMANDO_AO_A_GESTOR_A_VALOR_VALOR_UM_PEDIDO_DE_ANALISE_PARA_POSTERIOR_ENCAMINHAMENTO_A_SUB: " Enviaremos email informando ao(a) gestor(a) {p0} ({p1}) um pedido de análise para posterior encaminhamento à SUBCAP/SEP. ",
  ENVIO_DE_AVISO_DE_COMPLEMENTACAO_INICIADO_NO_E_DOCS: "Envio de aviso de complementação iniciado no E-Docs.",
  EQUATORIANO: "Equatoriano",
  EQUIPE_DE_CAPTACAO: "Equipe de Captação",
  EQUIPE_DE_ELABORACAO: "Equipe de Elaboração",
  EQUIPE_ELABORACAO_DEVE_CONTER_PELO_MENOS_UM_MEMBRO: "Equipe elaboração deve conter pelo menos um membro.",
  ERRO_AO_CARREGAR_PROJETO: "Erro ao carregar projeto",
  ERRO_AO_CONSULTAR_ANDAMENTO_DA_INTEGRACAO_COM_O_E_DOCS: "Erro ao consultar andamento da integração com o E-Docs.",
  ERRO_AO_INICIAR_AUTUACAO_NO_E_DOCS: "Erro ao iniciar autuação no E-Docs.",
  ERRO_AO_INICIAR_ENTRANHAMENTO_DE_PARECERES_DO_DIC_NO_E_DOCS: "Erro ao iniciar entranhamento de pareceres do DIC no E-Docs.",
  ERRO_AO_INICIAR_O_ENVIO_DE_AVISO_DE_COMPLEMENTACAO: "Erro ao iniciar o envio de aviso de complementação.",
  ERRO_AO_PROCESSAR_A_REQUISICAO: "Erro ao processar a requisição.",
  ERRO_AO_PROSSEGUIR_COM_EXCLUSAO: "Erro ao prosseguir com exclusão.",
  ERRO_AO_REENVIAR_E_MAIL_DE_PEDIDO_DE_PARECER: "Erro ao reenviar e-mail de pedido de parecer.",
  ESCOCES: "Escocês",
  ESLOVACO: "Eslovaco",
  ESLOVENO: "Esloveno",
  ESPANHOL: "Espanhol",
  ESSA_ACAO_NAO_PODERA_SER_DESFEITA_TEM_CERTEZA_QUE_DESEJA_CONTINUAR: "Essa ação não poderá ser desfeita. Tem certeza que deseja continuar?",
  ESTA_ACAO_DEFINIRA_A_ELEGIBILIDADE_DO_DIC_ASSINANDO_E_CAPTURANDO_O_PARECER_NO_E_DOCS_USANDO_SUA_IDENTIDADE_VAL: " Esta ação definirá a elegibilidade do DIC, assinando e capturando o parecer no E-Docs usando sua identidade - {p0} ({p1}). Após isso, o processo {p2} será encerrado no E-Docs. ",
  ESTA_ACAO_REALIZARA_A_CAPTURA_E_ASSINATURA_DO_PARECER_NO_E_DOCS_USANDO_A_SUA_IDENTIDADE_VALOR_VALOR_APOS_ISSO: " Esta ação realizará a captura e assinatura do parecer no E-Docs, usando a sua identidade - {p0} ({p1}). Após isso, o parecer não poderá mais ser editado ",
  ESTA_ACAO_REALIZARA_NO_E_DOCS_A_ASSINATURA_DO_DIC_E_A_AUTUACAO_DO_PROCESSO_DE_ELEGIBILIDADE_DO_PROJETO_UTILIZA: " Esta ação realizará no E-Docs a assinatura do DIC e a autuação do processo de elegibilidade do projeto, utilizando a sua identidade - {p0} ({p1}) ",
  ESTA_ACAO_REALIZARA_O_ENTRANHAMENTO_DOS_PARECERES_ORCAMENTARIO_E_ESTRATEGICO_AO_PROCESSO_VALOR_UTILIZANDO_A_SU: " Esta ação realizará o entranhamento dos pareceres orçamentário e estratégico ao processo {p0} utilizando a sua identidade - {p1} ({p2}). ",
  ESTA_ACAO_SOLICITARA_POR_EMAIL_AUTORIZACAO_PARA_O_PROGRAMA_AOS_GESTORES: "Esta ação solicitará por email autorização para o programa aos gestores",
  ESTADO: "Estado",
  ESTADO_2: "-- Estado --",
  ESTATISTICO: "Estatístico",
  ESTIMADO: "Estimado",
  ESTRATEGICO: "Estratégico",
  EX: "Ex: %",
  EX_25_000_2022: "Ex: 25.000 (2022)",
  EX_SECRETARIA_DE_EDUCACAO: "Ex: Secretaria de Educação",
  EX_TAXA_DE_ALFABETIZACAO: "Ex: Taxa de Alfabetização",
  EXCLUIR: "Excluir",
  EXCLUIR_ANEXO: "Excluir anexo",
  EXCLUIR_MEMBRO_DA_EQUIPE: "Excluir membro da equipe",
  EXCLUIR_ORGAO: "Excluir órgão",
  EXECUTOR: "Executor",
  EXPORTAR: "Exportar",
  FECHAR: "Fechar",
  FEMININO: "Feminino",
  FEV: "Fev",
  FEVEREIRO: "Fevereiro",
  FILTRAR: "FILTRAR",
  FILTRAR_ADICIONAR_POR_ODS: "Filtrar / Adicionar por ODS:",
  FILTROS: "Filtros",
  FILTROS_DE_INDICADORES: "Filtros de indicadores",
  FILTROS_DE_PLANEJAMENTO: "Filtros de planejamento",
  FONTE: "FONTE",
  FONTE_2: "FONTE:",
  FONTE_3: "Fonte",
  FORMATOS_ACEITOS: "Formatos aceitos:",
  FORMULA_METODOLOGIA_DE_CALCULO: "FÓRMULA / METODOLOGIA DE CÁLCULO",
  FORMULA_METODOLOGIA_DE_CALCULO_2: "FÓRMULA / METODOLOGIA DE CÁLCULO:",
  FOTO_DE_PERFIL: "Foto de Perfil",
  FRANCES: "Francês",
  FUNCAO: "Função",
  FUNCAO_2: "FUNÇÃO",
  GALES: "Galês",
  GANES: "Ganés",
  GERAL: "Geral",
  GESTAO_ADMINISTRATIVA: "GESTÃO ADMINISTRATIVA",
  GESTAO_ADMINISTRATIVA_2: "Gestão Administrativa",
  GESTOR: "Gestor",
  GESTOR_PROPONENTE: "Gestor Proponente",
  GIRAR_PARA_A_DIREITA: "Girar para a direita",
  GIRAR_PARA_A_ESQUERDA: "Girar para a esquerda",
  GND: "GND",
  GRANADINO: "Granadino",
  GREGO: "Grego",
  GRUPOS_DE_USUARIOS: "Grupos de Usuários",
  GUATEMALTECO: "Guatemalteco",
  GUIANENSE: "Guianense",
  GUIANES: "Guianês",
  HAITIANO: "Haitiano",
  HOLANDES: "Holandês",
  HONDURENHO: "Hondurenho",
  HUNGARO: "Húngaro",
  I_APONTAR_QUAIS_AREAS_ESTRATEGICAS_REFERIDAS_NO_PLANEJAMENTO_ESTRATEGICO_SAO_ATENDIDAS_PELO_DIC_APONTAR_SE_O_P: "(i) Apontar quais áreas estratégicas referidas no Planejamento Estratégico são atendidas pelo DIC. Apontar se o programa ou DIC é destinado ao atendimento de uma ou mais das prioridades da Administração Pública. (ii) Demonstrar a inserção do DIC no Plano Plurianual (PPA) vigente, identificando os programas e ações para os quais o DIC está previsto. (iii) Indicar a previsão orçamentária do DIC na Lei Orçamentária Anual (LOA) vigente, identificando as fontes, as ações e os valores respectivos que estão previstos para o DIC.",
  I_INFORMAR_AS_INSTITUICOES_ENVOLVIDAS_NA_IMPLEMENTACAO_DO_PROJETO_E_SUAS_RESPECTIVAS_RESPONSABILIDADES_NA_EXEC: "(i) Informar as instituições envolvidas na implementação do projeto e suas respectivas responsabilidades na execução. (ii) Informar a capacidade das insituições para a implementação das ações do projeto (equipe técnica, estrutura, experiência).",
  I_INFORMAR_O_ORGAO_EXECUTOR_PRINCIPAL_DO_PROGRAMA_OU_DIC_E_DEMAIS_ORGAOS_PARTICIPANTES_SE_EXISTENTES_II_INFORM: "(i) Informar o órgão executor principal do programa ou DIC e demais órgãos participantes, se existentes. (ii) informar a capacidade das instituições proponentes, em particular do órgão executor, para a implementação das ações do programa ou projeto, como qualificação e experiência da equipe técnica e recursos e estruturas disponíveis. (iii) Apontar se haverá repasse de recursos entre os órgãos participantes.",
  ID_USO: "ID-USO",
  IDENTIFICAR_INDICADORES_ESTRATEGICOS_QUE_POSSAM_SER_ASSOCIADOS_AO_PROJETO_EM_ANALISE: "Identificar indicadores estratégicos que possam ser associados ao projeto em análise.",
  IDENTIFICAR_O_S_PROBLEMA_S_QUE_AS_ACOES_DO_DIC_CANDIDATO_A_FINANCIAMENTO_SE_PROPOEM_SOLUCIONAR_OU_MINORAR_DESC: "Identificar o(s) problema(s) que as ações do DIC candidato a financiamento se propõem solucionar ou minorar. Descrever clara e sucintamente a situação-problema atual, apresentando informações e dados que a caracterizem e demonstrem o(s) problema(s). Trata-se da situação inicial que se deseja mudar.",
  IDENTIFIQUE_A_INSTITUICAO_SECRETARIA_DE_ESTADO_AUTARQUIA_ORGAO_DE_OUTROS_PODERES_DO_ESTADO_ETC_QUE_SERA_O_TOMA: "Identifique a instituição (Secretaria de Estado, Autarquia, Órgão de outros poderes do Estado, etc.) que será o tomador dos recursos, gestor do DIC.",
  IEMENITA: "Iemenita",
  IMAGEM: "Imagem",
  IMAGEM_DA_ORGANIZACAO: "Imagem da organizacao",
  IMAGEM_DA_PESSOA: "Imagem da pessoa",
  IMPACTOS: "Impactos",
  IMPACTOS_DO_PROJETO_NO_AMBITO_AMBIENTAL_SOCIAL_E_DE_GOVERNANCA_ESG: "Impactos do Projeto no Âmbito Ambiental, Social e de Governança (ESG)",
  IMPORTAR: "Importar",
  IMPORTAR_PESSOA_DO_ACESSO_CIDADAO: "Importar pessoa do Acesso Cidadão",
  IMPOSSIVEL_ASSINAR_O_PROGRAMA_POIS_UM_DOS_ASSINANTES_JA_O_RECUSOU: "Impossível assinar o Programa pois um dos assinantes já o Recusou",
  INDIANO: "Indiano",
  INDICADOR: "Indicador",
  INDICADOR_DE_PROJETO: "INDICADOR DE PROJETO",
  INDICADOR_DE_PROJETO_2: "(Indicador de projeto)",
  INDICADOR_REMOVIDO_DO_PROJETO: "Indicador removido do projeto.",
  INDICADORES: "Indicadores",
  INDICADORES_SELECIONADOS: "INDICADORES SELECIONADOS",
  INDICADORES_VINCULADOS: "Indicadores Vinculados",
  INDICAR_A_DISPONIBILIDADE_DE_OUTRAS_FONTES_DE_RECURSOS_EVENTUALMENTE_ACESSIVEIS_AO_ORGAO_DEMANDANTE: "Indicar a disponibilidade de outras fontes de recursos eventualmente acessíveis ao Órgão demandante.",
  INDICAR_E_OU_CONFIRMAR_O_ENQUADRAMENTO_DO_PROJETO_EM_RELACAO_AO_PLANEJAMENTO_ESTRATEGICO_DO_GOVERNO_VIGENTE_EI: "Indicar e/ou confirmar o enquadramento do projeto em relação ao Planejamento Estratégico do Governo vigente (eixo, área estratégica, programa ou afins);",
  INDICAR_O_NOME_FANTASIA_DO_DIC: "Indicar o nome fantasia do DIC.",
  INDICAR_O_VALOR_TOTAL_NECESSARIO_PARA_A_EXECUCAO_DO_DIC_PROPOSTO_EM_R: "Indicar o valor total necessário para a execução do DIC proposto em R$.",
  INDONESIO: "Indonésio",
  INFORMACOES_DA_ORGANIZACAO: "Informações da Organização",
  INFORMACOES_PESSOAIS: "Informações Pessoais",
  INFORMACOES_PROFISSIONAIS: "Informações Profissionais",
  INFORMAR_A_JUSTIFICATIVA_PARA_ARQUIVAMENTO: "-- Informar a justificativa para arquivamento --",
  INFORMAR_A_JUSTIFICATIVA_PARA_REVISAO: "-- Informar a justificativa para revisão --",
  INFORMAR_I_AS_MEDIDAS_DE_SUSTENTABILIDADE_A_SEREM_ADOTADAS_E_OS_CUSTOS_ADICIONAIS_ESTIMADOS_DECORRENTES_DA_IMP: "Informar (i) as medidas de sustentabilidade a serem adotadas e os custos adicionais estimados decorrentes da implementação do programa/DIC, referentes aos gastos incrementais de pessoal, de operacionalização e de manutenção de obras e bens; (ii) os principais impactos ambientais decorrentes da implementação do DIC; (iii) possíveis interferências em populações decorrentes da implementação do programa/DIC. Especificar se há interferência em populações indígenas, quilombolas e outras; e (iv) os riscos e ações mitigadoras.",
  INFORMAR_O_NOME_DO_DIC_O_NOME_DEVERA_REFLETIR_O_OBJETIVO_MAIOR_DO_DIC: "Informar o nome do DIC. O nome deverá refletir o objetivo maior do DIC.",
  INFORME_O_ANO_ANTES_DE_ADICIONAR_UMA_ACAO: "Informe o ano antes de adicionar uma ação.",
  INFORME_O_MOTIVO_PARA_ARQUIVAMENTO: "Informe o motivo para arquivamento.",
  INFORME_O_MOTIVO_PARA_COMPLEMENTACAO: "Informe o motivo para complementação.",
  INFORME_PELO_MENOS_UM_INDICADOR: "Informe pelo menos um indicador.",
  INFORME_PELO_MENOS_UM_MEMBRO_ATIVO_ALEM_DO_REDATOR: "Informe pelo menos um membro ativo além do Redator.",
  INFORME_PELO_MENOS_UM_NOME_COM_NO_MINIMO_3_CARACTERES: "Informe pelo menos um nome com no mínimo 3 caracteres.",
  INFORME_UMA_ACAO_DE_PLANEJAMENTO_OU_MARQUE_QUE_O_PROJETO_NAO_ESTA_PREVISTO_NO_PPA: "Informe uma ação de planejamento ou marque que o projeto não está previsto no PPA.",
  INGLES: "Inglês",
  INSERIR_AS_ACOES_SECUNDARIAS_SE_HOUVER_E_OS_PRODUTOS_OS_PRODUTOS_DEVERAO_COMPREENDER_OS_BENS_OU_SERVICOS_OFERE: "Inserir as ações secundárias, se houver, e os produtos. Os produtos deverão compreender os bens ou serviços oferecidos pelo DIC e estar associados à etapa ou subetapa, conforme o caso.",
  INSERIR_O_NOME_DA_ACAO: "Inserir o nome da ação.",
  INSIRA_O_TEXTO_AQUI: "-- Insira o texto aqui --",
  INTERESSADO_A_S: "Interessado(a) s",
  INTERESSADO_A_S_2: "Interessado(a)(s):",
  INVERTER_POSICAO_HORIZONTAL: "Inverter posição horizontal",
  INVERTER_POSICAO_VERTICAL: "Inverter posição vertical",
  IR_PARA_O_CAMPO: "Ir para o campo",
  IRANIANO: "Iraniano",
  IRAQUIANO: "Iraquiano",
  IRLANDES: "Irlandês",
  ISRAELITA: "Israelita",
  ITALIANO: "Italiano",
  ITALICO: "Itálico",
  JAMAICANO: "Jamaicano",
  JAN: "Jan",
  JANEIRO: "Janeiro",
  JAPONES: "Japonês",
  JPEG_JPG_GIF_OU_PNG: "JPEG, JPG, GIF ou PNG.",
  JUL: "Jul",
  JULHO: "Julho",
  JUN: "Jun",
  JUNHO: "Junho",
  JUSTIFICATIVA: "Justificativa",
  JUSTIFICATIVA_2: "Justificativa:",
  LIBIO: "Líbio",
  LIMPANDO_MEMBROS_DA_EQUIPE: "Limpando membros da equipe.",
  LIMPANDO_OS_INTERESSADOS: "Limpando os interessados.",
  LIMPAR: "Limpar",
  LINK: "Link",
  LISTA_DE_DICS_ELEGIVEIS_PARA_VINCULACAO_A_UM_PROGRAMA: "Lista de DICs elegíveis para vinculação a um programa.",
  LISTA_NAO_ORDENADA: "Lista não ordenada",
  LISTA_ORDENADA: "Lista ordenada",
  LOGIN: "Login",
  MAI: "Mai",
  MAIO: "Maio",
  MALAIO: "Malaio",
  MAR: "Mar",
  MARCA_DA_ORGANIZACAO: "Marca da Organização",
  MARCO: "Março",
  MARFINENSE: "Marfinense",
  MARROQUINO: "Marroquino",
  MASCULINO: "Masculino",
  MATRIZ_SEDE: "Matriz / Sede",
  MATRIZ_SEDE_2: "-- Matriz/Sede --",
  MEMBRO_EXCLUIDO_DA_EQUIPE: "Membro excluído da equipe.",
  MEMBRO_REMOVIDO_DA_EQUIPE: "Membro removido da equipe.",
  META: "META:",
  META_2: "Meta",
  META_DO_PROJETO: "META DO PROJETO",
  META_DO_PROJETO_2: "META DO PROJETO:",
  METAS_DOS_INDICADORES: "Metas dos Indicadores",
  MEU_PERFIL: "Meu Perfil",
  MEXICANO: "Mexicano",
  MINHA_AUTORIZACAO: "Minha Autorização",
  MOCAMBICANO: "Moçambicano",
  MODALIDADE: "Modalidade",
  MOEDA: "Moeda",
  MOEDA_2: "-- Moeda --",
  MOSTRANDO_VALOR_ATE_VALOR_REGISTROS_DE_VALOR: " Mostrando {p0} até {p1} registros de {p2} ",
  MOTIVO_ARQUIVAMENTO: "Motivo Arquivamento",
  MOVER_PARA_A_DIREITA: "Mover para a direita",
  MOVER_PARA_A_ESQUERDA: "Mover para a esquerda",
  MOVER_PARA_BAIXO: "Mover para baixo",
  MOVER_PARA_CIMA: "Mover para cima",
  NACIONALIDADE: "Nacionalidade",
  NACIONALIDADE_2: "-- Nacionalidade --",
  NAO_AUTORIZO: "Não Autorizo",
  NAO_E_POSSIVEL_ALTERAR_OS_DADOS_DE_UMA_CARTA_CONSULTA_PERTENCENTE_A_UMA_PROSPECCAO_QUE_JA_FOI_PROSPECTADA: "Não é possível alterar os dados de uma carta consulta pertencente á uma prospecção que já foi prospectada.",
  NAO_E_POSSIVEL_ALTERAR_OS_DADOS_DE_UMA_PROSPECCAO_QUE_JA_FOI_PROSPECTADA: "Não é possível alterar os dados de uma prospecção que já foi prospectada.",
  NAO_E_POSSIVEL_EXCLUIR_UMA_CARTA_CONSULTA_PERTENCENTE_A_UMA_PROSPECCAO_QUE_JA_FOI_PROSPECTADA: "Não é possível excluir uma carta consulta pertencente á uma prospecção que já foi prospectada.",
  NAO_E_POSSIVEL_EXCLUIR_UMA_PROSPECCAO_QUE_JA_FOI_PROSPECTADA: "Não é possível excluir uma prospecção que já foi prospectada.",
  NAO_E_POSSIVEL_VINCULAR_O_PROJETO_A_ESTE_PROGRAMA_ATE_QUE_O_PARECER_DE_CAPTACAO_SEJA_ENVIADO_PARA_SUBCAP: "Não é possível vincular o projeto á este programa até que o parecer de captação seja enviado para SUBCAP!",
  NAO_EXISTEM_ASSINATURAS_PENDENTES_PARA_ESTE_PROGRAMA_E_NECESSARIO_SOLICITAR_AUTORIZACAO_PRIMEIRO: "Não existem assinaturas pendentes para este Programa. É necessário Solicitar Autorização primeiro.",
  NAO_FOI_POSSIVEL_CONSULTAR_OS_DADOS_DAS_ACOES_SELECIONADAS: "Não foi possível consultar os dados das ações selecionadas.",
  NAO_PREVISTO_NO_PPA_VALOR: " Não previsto no PPA {p0} ",
  NEGRITO: "Negrito",
  NENHUM_AGENTE_ENCONTRADO: "Nenhum agente encontrado.",
  NENHUM_COMPLEMENTO_INFORMADO: "Nenhum complemento informado.",
  NENHUM_INDICADOR_ENCONTRADO: "Nenhum indicador encontrado",
  NENHUM_INDICADOR_SELECIONADO: "Nenhum indicador selecionado.",
  NENHUM_ITEM_ENCONTRADO: "Nenhum item encontrado.",
  NENHUM_RESULTADO_ENCONTRADO: "Nenhum resultado encontrado.",
  NENHUMA_ACAO_ENCONTRADA_PARA_O_FILTRO_INFORMADO: "Nenhuma ação encontrada para o filtro informado.",
  NENHUMA_ACAO_SELECIONADA: "Nenhuma ação selecionada",
  NENHUMA_PENDENCIA_OBRIGATORIA_FOI_ENCONTRADA: "Nenhuma pendência obrigatória foi encontrada.",
  NEOZELANDES: "Neozelandês",
  NEPALES: "Nepalês",
  NICARAGUENSE: "Nicaraguense",
  NIGERIANO: "Nigeriano",
  NO_DIA: "no dia",
  NOME: "Nome",
  NOME_COMPLETO: "Nome Completo",
  NOME_DA_ACAO: "Nome da ação",
  NOME_DA_ODS: "Nome da ODS",
  NOME_DO_INDICADOR: "NOME DO INDICADOR",
  NOME_DO_INDICADOR_2: "Nome do indicador",
  NOME_RAZAO_SOCIAL: "Nome / Razão Social",
  NOME_SOCIAL: "Nome Social",
  NORTE_COREANO_COREANO: "Norte-coreano, coreano",
  NORUEGO: "Noruego",
  NOV: "Nov",
  NOVA_ORGANIZACAO: "Nova Organização",
  NOVA_PESQUISA_DE_FONTE_DE_FINANCIAMENTO: "Nova Pesquisa de Fonte de Financiamento",
  NOVA_PESQUISA_FONTE_FINANCIAMENTO: "Nova Pesquisa Fonte Financiamento",
  NOVA_PESSOA: "Nova Pessoa",
  NOVA_PROSPECCAO: "Nova Prospecção",
  NOVEMBRO: "Novembro",
  NOVO_DIC: "Novo DIC",
  NOVO_DIC_DOCUMENTO_INICIAL_DE_CAPTACAO: "Novo DIC (Documento Inicial de Captação)",
  NOVO_PROGRAMA: "Novo Programa",
  NOVO_STATUS: "Novo Status",
  O_ARQUIVO_SELECIONADO_NAO_E_UM_PDF_VALIDO: "O arquivo selecionado não é um PDF válido.",
  O_DIC_SELECIONADO_JA_ESTA_VINCULADO_AO_SEGUINTE_PROGRAMA: "O DIC selecionado já está vinculado ao seguinte Programa:",
  O_FORMULARIO_CONTEM_ERROS: "O formulário contém erros.",
  O_PROJETO_POSSUI_CAMPOS_OBRIGATORIOS_OU_INFORMACOES_INCOMPLETAS: "O projeto possui campos obrigatórios ou informações incompletas.",
  O_PROJETO_SELECIONADO_NAO_POSSUI_PARECER_DE_CAPTACAO_ENVIADO: "O projeto selecionado não possui parecer de captação enviado.",
  O_SETOR_DEVERA_ELABORAR_UM_PARECER_ESTRATEGICO_ACERCA_DO_PROJETO_APRESENTADO_CONTEMPLANDO_OS_SEGUINTES_PONTOS: "O setor deverá elaborar um parecer estratégico acerca do projeto apresentado, contemplando os seguintes pontos:",
  O_SETOR_RESPONSAVEL_DEVERA_APRESENTAR_PARECER_QUANTO_A_ADEQUACAO_ORCAMENTARIA_DA_PROPOSTA_ABRANGENDO_OS_SEGUIN: "O setor responsável deverá apresentar parecer quanto à adequação orçamentária da proposta, abrangendo os seguintes aspectos:",
  O_SETOR_RESPONSAVEL_DEVERA_ELABORAR_PARECER_ACERCA_DA_PROPOSTA_CONTEMPLANDO_OS_SEGUINTES_ASPECTOS: "O setor responsável deverá elaborar parecer acerca da proposta, contemplando os seguintes aspectos:",
  O_SISCAP_ENVIARA_UM_EMAIL_AUTOMATICO_A_AMBAS: "O Siscap enviará um email automático a ambas.",
  OBJETIVO: "Objetivo",
  OBJETIVO_ESPECIFICO: "Objetivo Específico",
  OBJETIVO_GERAL: "Objetivo Geral",
  OBJETIVOS_ESPECIFICOS: "Objetivos Específicos",
  OBJETO: "Objeto:",
  OBJETO_2: "Objeto",
  OBRIGATORIO_INFORMAR_ANO_E_UO_PARA_CARREGAMENTO_DAS_ACOES: "Obrigatório informar ano e uo para carregamento das açoes.",
  OCORREU_ALGUM_ERRO_AO_CARREGAR_AS_ASSINATURAS: "Ocorreu algum erro ao carregar as assinaturas",
  OCORREU_ERRO_NA_INTEGRACAO_COM_O_E_DOCS: "Ocorreu erro na integração com o E-Docs.",
  OCORREU_UM_ERRO: "Ocorreu um erro",
  OCORREU_UM_ERRO_2: "Ocorreu um erro!",
  OCORREU_UM_ERRO_AO_TENTAR_ASSINAR_O_PROGRAMA: "Ocorreu um erro ao tentar assinar o Programa!",
  OCORREU_UM_ERRO_AO_TENTAR_ATUALIZAR_O_PROGRAMA: "Ocorreu um erro ao tentar atualizar o Programa",
  OCORREU_UM_ERRO_AO_TENTAR_AUTUAR_O_PROGRAMA: "Ocorreu um erro ao tentar Autuar o Programa!",
  OCORREU_UM_ERRO_AO_TENTAR_AUTUAR_O_PROGRAMA_2: "Ocorreu um erro ao tentar Autuar o programa!",
  OCORREU_UM_ERRO_AO_TENTAR_EXPORTAR_O_PROGRAMA: "Ocorreu um erro ao tentar exportar o Programa",
  OCORREU_UM_ERRO_AO_TENTAR_PROCESSAR_AS_AUTORIZACOES: "Ocorreu um erro ao tentar processar as Autorizações!",
  OCORREU_UM_ERRO_AO_TENTAR_RECUSAR_A_ASSINATURA_DO_PROGRAMA: "Ocorreu um erro ao tentar recusar a assinatura do Programa!",
  OCORREU_UM_ERRO_AO_TENTAR_SOLICITAR_AS_AUTORIZACOES_DO_PROGRAMA: "Ocorreu um erro ao tentar solicitar as Autorizações do Programa",
  OCORREU_UM_ERRO_NA_INTEGRACAO_COM_O_E_DOCS: "Ocorreu um erro na integração com o E-Docs",
  ODS: "ODS",
  ODS_CONFIRMADAS_PARA_ESTE_PROJETO_CLIQUE_EM_PARA_REMOVER: "ODS confirmadas para este projeto. Clique em × para remover.",
  ODS_IDENTIFICADAS_A_PARTIR_DOS_INDICADORES_SELECIONADOS_CLIQUE_PARA_ADICIONAR_A_SELECAO: "ODS identificadas a partir dos indicadores selecionados. Clique para adicionar à seleção.",
  ODS_SELECIONADAS: "ODS Selecionadas",
  ODS_SUGERIDAS: "ODS Sugeridas",
  OK: "OK",
  OMANENSE: "Omanense",
  OPERACAO: "Operação",
  OPERACAO_2: "Operação:",
  OPORTUNIDADE: "Oportunidade",
  ORCAMENTARIO: "Orçamentário",
  ORGANIZACAO: "Organização",
  ORGANIZACAO_ALTERADA_COM_SUCESSO: "Organização alterada com sucesso.",
  ORGANIZACAO_CADASTRADA_COM_SUCESSO: "Organização cadastrada com sucesso.",
  ORGANIZACAO_PROSPECTADA: "Organização Prospectada",
  ORGANIZACAO_PROSPECTADA_ALTERADA: "Organização prospectada alterada",
  ORGANIZACAO_PROSPECTORA: "Organização Prospectora",
  ORGANIZACOES: "Organizações",
  ORGANIZACOES_2: "-- Organizações --",
  ORGANIZACOES_3: "Organizacoes",
  ORGAO: "Órgão",
  ORGAOS_ENVOLVIDOS: "Orgãos Envolvidos",
  OUT: "Out",
  OUTRO: "Outro",
  OUTUBRO: "Outubro",
  PAGINA_PRINCIPAL: "Página Principal",
  PAIS: "-- País --",
  PAIS_DE_ORIGEM: "País de Origem",
  PALESTINO: "Palestino",
  PANAMENHO: "Panamenho",
  PAPEL_DO_ORGAO: "-- Papel do órgão --",
  PAQUISTANES: "Paquistanês",
  PARA: "Para:",
  PARA_ACESSAR_DIRETAMENTE_A_SECAO_ONDE_A_PENDENCIA_DEVE_SER_CORRIGIDA: "para acessar diretamente a seção onde a pendência deve ser corrigida.",
  PARAGUAIO: "Paraguaio",
  PARAMETRO_BYTES: "{p0} bytes",
  PARAMETRO_DEVE_POSSUIR_NO_MAXIMO_PARAMETRO_CARACTERES: "{p0} deve possuir no máximo {p1} caracteres.",
  PARAMETRO_DEVE_POSSUIR_NO_MINIMO_PARAMETRO_CARACTERES: "{p0} deve possuir no mínimo {p1} caracteres.",
  PARAMETRO_E_OBRIGATORIO: "{p0} é obrigatório.",
  PARAMETRO_KB: "{p0} KB",
  PARAMETRO_MB: "{p0} MB",
  PARAMETRO_POSSUI_INFORMACAO_INVALIDA: "{p0} possui informação inválida.",
  PARAMETRO_SELECIONADOS: "{p0} selecionados",
  PARECER: "Parecer",
  PARECER_2: "Parecer:",
  PARECER_ANEXADO_EM_PDF: "Parecer anexado em PDF.",
  PARECER_CAPTACAO: "Parecer Captação",
  PARECER_ENVIADO: "Parecer enviado",
  PARECER_ESTRATEGICO: "Parecer Estratégico",
  PARECER_ORCAMENTARIO: "Parecer Orçamentário",
  PARECER_ORCAMENTARIO_BR_PARECER_ESTRATEGICO: "Parecer Orçamentário<br/>Parecer Estratégico",
  PARECER_VALOR: " Parecer {p0} ",
  PARECERES: "Pareceres",
  PARTES_INTERESSADAS: "Partes Interessadas",
  PECAS_DE_PLANEJAMENTO: "Peças de Planejamento",
  PECAS_DO_PLANEJAMENTO: "Peças do Planejamento",
  PEDIR_PARECER: "Pedir Parecer",
  PENDENCIAS: "Pendências",
  PENDENCIAS_DO_PROJETO: "Pendências do projeto",
  PENDENTE: "Pendente",
  PENDENTE_2: "Pendente...",
  PERFIL_ATUALIZADO_COM_SUCESSO: "Perfil atualizado com sucesso.",
  PERFIL_DO_USUARIO: "Perfil do Usuario",
  PERUANO: "Peruano",
  PESQUISA: "Pesquisa",
  PESQUISA_DE_FONTES_DE_FINANCIAMENTO: "Pesquisa de Fontes de Financiamento",
  PESQUISA_DE_FONTES_DE_FINANCIAMENTO_1: "Pesquisa de Fontes de Financiamento-1",
  PESQUISAR: "Pesquisar",
  PESSOA_ALTERADA_COM_SUCESSO: "Pessoa alterada com sucesso.",
  PESSOA_CADASTRADA_COM_SUCESSO: "Pessoa cadastrada com sucesso.",
  PESSOA_JA_INCLUSO_NA_EQUIPE: "Pessoa já incluso na equipe",
  PESSOA_QUE_RESPONDE_PELO_ORGAO_DE_ORIGEM: "Pessoa que responde pelo órgão de origem.",
  PESSOAS: "Pessoas",
  PESSOAS_RESPONSAVEIS_PELA_ELABORACAO_DO_DIC: "Pessoas responsáveis pela elaboração do DIC.",
  PLANEJAMENTO: "Planejamento",
  PLANEJAMENTO_2: "PLANEJAMENTO",
  PLANEJAMENTO_PPA: "Planejamento PPA",
  POLONES: "Polonês",
  POR: "por",
  POR_FAVOR_PREENCHA_A_JUSTIFICATIVA_ANTES_DE_PROSSEGUIR: "Por favor, preencha a justificativa antes de prosseguir.",
  POR_FAVOR_VERIFIQUE_OS_CAMPOS: "Por favor, verifique os campos.",
  POR_VALOR: "Por: {p0}",
  PORTORRIQUENHO: "Portorriquenho",
  PORTUGUES: "Português",
  PREENCHA_TODAS_AS_METAS_DOS_INDICADORES: "Preencha todas as metas dos indicadores.",
  PREENCHER_O_VALOR_ESTIMADO_TOTAL_A_SER_DESTINADO_A_IMPLANTACAO_DAS_ACOES_PRINCIPAIS_O_VALOR_DEVERA_SER_COMPATI: "Preencher o valor estimado total a ser destinado à implantação das ações principais. O valor deverá ser compatível com o objeto.",
  PREFERENCIALMENTE_DEVERAO_SER_CONSIDERADOS_OS_INDICADORES_CHAVE_NACIONAIS_CONSTANTES_DO_PLANO_PLURIANUAL_2024: "Preferencialmente deverão ser considerados os indicadores-chave nacionais constantes do Plano Plurianual 2024-2027, além de outros indicadores relacionados ao DIC.",
  PRIMEIRO: "Primeiro",
  PROCESSANDO: "Processando",
  PROCESSANDO_2: "Processando...",
  PROCESSO: "Processo",
  PROCESSO_AUTUADO_E_ENCAMINHADO_COM_SUCESSO: "PROCESSO AUTUADO E ENCAMINHADO COM SUCESSO!",
  PROCESSO_DE_AUTUACAO_INICIADO_NO_E_DOCS: "Processo de autuação iniciado no E-Docs.",
  PROCESSO_DE_ENTRANHAMENTO_DE_PARECERES_DO_DIC_INICIADO_NO_E_DOCS: "Processo de entranhamento de pareceres do DIC iniciado no E-Docs.",
  PROCESSO_E_DOCS: "Processo E-Docs",
  PROCESSO_REENTRANHAR_DIC_COM_CORRECOES_INICIADO_NO_E_DOCS: "Processo reentranhar DIC com correções iniciado no E-Docs.",
  PROGRAMA: "Programa",
  PROGRAMA_2: "PROGRAMA",
  PROGRAMA_ALTERADO_COM_SUCESSO: "Programa alterado com sucesso.",
  PROGRAMA_CADASTRADO_COM_SUCESSO: "Programa cadastrado com sucesso.",
  PROGRAMA_DEVE_CONTER_AO_MENOS_UM_ORGAO_GESTOR: "Programa deve conter ao menos um Órgão Gestor.",
  PROGRAMA_EXPORTADO_COM_SUCESSO: "Programa exportado com sucesso!",
  PROGRAMAS: "Programas",
  PROGRESSO: "Progresso",
  PROJETO_ALTERADO_COM_SUCESSO: "Projeto alterado com sucesso.",
  PROJETO_CADASTRADO_COM_SUCESSO: "Projeto cadastrado com sucesso.",
  PROJETO_PREENCHIDO_CORRETAMENTE: "Projeto preenchido corretamente.",
  PROJETOS: "Projetos",
  PROPONENTE: "Proponente",
  PROSPECCAO: "Prospecção",
  PROSPECCAO_2: "Prospecção:",
  PROSPECCAO_ALTERADA_COM_SUCESSO: "Prospecção alterada com sucesso.",
  PROSPECCAO_CADASTRADA_COM_SUCESSO: "Prospecção cadastrada com sucesso.",
  PROSPECTAR: "Prospectar",
  PROSPECTOR: "Prospector",
  PROSSEGUIR: "Prosseguir",
  PROXIMO: "Próximo",
  QATARENSE: "Qatarense",
  QUA: "Qua",
  QUENIANO: "Queniano",
  QUI: "Qui",
  RATEIO: "Rateio",
  RECUSA_REGISTRADA_COM_SUCESSO: "Recusa registrada com sucesso",
  RECUSADO: "Recusado",
  RECUSAR: "Recusar",
  REDUZIR_O_ZOOM: "Reduzir o zoom",
  REENVIANDO_PEDIDO_PARECER: "Reenviando pedido parecer...",
  REGIOES_GEOGRAFICAS_ATENDIDAS: "Regiões Geográficas Atendidas",
  RELATORIOS: "Relatórios",
  REMOVER: "Remover",
  REMOVER_ACAO: "Remover ação",
  REMOVER_ACAO_DO_DIC: "Remover Ação do DIC",
  REMOVER_ACAO_DO_PLANEJAMENTO: "Remover ação do planejamento",
  REMOVER_FILTRO_NOME: 'Remover filtro {nome}',
  REMOVER_INDICADOR: "Remover indicador",
  REMOVER_INDICADOR_DE_PROJETO: "Remover indicador de projeto",
  REMOVER_INDICADOR_DO_DIC: "Remover Indicador do DIC",
  REMOVER_INTERESSADO_A: "Remover Interessado(a)",
  REMOVER_PROJETO_DO_PROGRAMA: "Remover Projeto do Programa",
  RESETAR_IMAGEM: "Resetar imagem",
  RESPONSAVEL: "Responsável",
  RESPONSAVEL_2: "-- Responsável --",
  RESPONSAVEL_PROPONENTE: "Responsável Proponente",
  RESPONSAVEL_PROPONENTE_JA_INCLUSO_NA_EQUIPE: "Responsável proponente já incluso na equipe",
  RESTAURAR_FILTROS: "RESTAURAR FILTROS",
  REVISAO_ERRO_DETALHE: 'Erro ao enviar revisão: {erro}',
  REVISAR: "Revisar",
  ROLAR_FILTROS_SELECIONADOS_PARA_A_DIREITA: "Rolar filtros selecionados para a direita",
  ROLAR_FILTROS_SELECIONADOS_PARA_A_ESQUERDA: "Rolar filtros selecionados para a esquerda",
  ROMENO: "Romeno",
  RUANDES: "Ruandês",
  RUSSO: "Russo",
  SAB: "Sab",
  SAIR: "Sair",
  SALVADORENHO: "Salvadorenho",
  SALVANDO_ALTERACOES: "Salvando alterações...",
  SALVANDO_PROJETO: "Salvando projeto...",
  SALVAR: "Salvar",
  SALVAR_E_ENVIAR: "Salvar e Enviar",
  SALVAR_PARECER: "Salvar Parecer",
  SAUDITA: "Saudita",
  SE_NAO_ENCONTRAR_O_INDICADOR_ESTRATEGICO_DESEJADO_CRIE_UM_NOVO: "Se não encontrar o indicador estratégico desejado, crie um novo",
  SECRETARIA_DE_ECONOMIA_E_PLANEJAMENTO_DO_ESPIRITO_SANTO: "Secretaria de Economia e Planejamento do Espírito Santo",
  SEG: "Seg",
  SELECIONAR: "Selecionar...",
  SELECIONAR_ODS: 'Clique para selecionar {nome}',
  SELECIONAR_TODOS: "SELECIONAR TODOS",
  SELECIONE: "Selecione...",
  SELECIONE_A_ACAO: "Selecione a ação",
  SELECIONE_A_CARTA_CONSULTA: "-- Selecione a carta consulta --",
  SELECIONE_A_ORGANIZACAO_PROSPECTADA: "-- Selecione a organização prospectada --",
  SELECIONE_A_ORGANIZACAO_PROSPECTORA: "-- Selecione a organização prospectora --",
  SELECIONE_DESTINATARIOS_DA_LISTA_ABAIXO: "-- Selecione destinatários da lista abaixo --",
  SELECIONE_O_INDICADOR_ESTRATEGICO: "SELECIONE O INDICADOR ESTRATÉGICO",
  SELECIONE_O_PROSPECTOR: "-- Selecione o prospector --",
  SELECIONE_O_RESPONSAVEL_PROPONENTE: "-- Selecione o responsável proponente --",
  SELECIONE_OS_ORGAOS_EXECUTORES_DO_PROGRAMA: "-- Selecione os orgãos executores do programa --",
  SELECIONE_UM_A_INTERESSADO_A: "-- Selecione um(a) interessado(a) --",
  SELECIONE_UM_DIC_PARA_INCLUIR_NO_PROGRAMA: "-- Selecione um DIC para incluir no programa --",
  SELECIONE_UM_MOTIVO_PARA_ARQUIVAMENTO: "-- Selecione um motivo para arquivamento--",
  SELECIONE_UM_OBJETO_DA_LISTA_ABAIXO: "-- Selecione um objeto da lista abaixo --",
  SELECIONE_UM_ORGAO_DA_LISTA_ABAIXO: "-- Selecione um orgão da lista abaixo --",
  SELECIONE_UMA_OPERACAO_DA_LISTA_ABAIXO: "-- Selecione uma operação da lista abaixo --",
  SEM_VALOR_ESTIMADO: "Sem Valor Estimado",
  SERVIO: "Sérvio",
  SET: "Set",
  SETEMBRO: "Setembro",
  SEX: "Sex",
  SIGLA: "Sigla",
  SIGLA_DO_DIC: "Sigla do DIC",
  SIGLA_DO_PROGRAMA: "Sigla do Programa",
  SIGLA_NOME_FANTASIA: "Sigla / Nome Fantasia",
  SIRIO: "Sírio",
  SISCAP_VALOR: " SISCAP {p0}",
  SISCAP_VALOR_SECRETARIA_DE_ECONOMIA_E_PLANEJAMENTO_DO_ESPIRITO_SANTO: " SISCAP {p0} - Secretaria de Economia e Planejamento do Espírito Santo",
  SITE: "Site",
  SITUACAO_PROBLEMA: "Situação Problema",
  SO_E_PERMITIDO_ADICIONAR_ACOES_DO_ANO_VALOR_REMOVA_AS_ACOES_ATUAIS_PARA_TROCAR_O_ANO: "Só é permitido adicionar ações do ano {p0}. Remova as ações atuais para trocar o ano.",
  SOLICITAR_AUTORIZACAO: "Solicitar Autorização",
  SOLICITAR_REVISAO_A_VALOR: "Solicitar revisão a {p0} ",
  SOLUCOES_PROPOSTAS: "Soluções Propostas",
  SOLUCOES_PROPOSTAS_RESULTADOS_ESPERADOS: "Soluções Propostas/Resultados Esperados",
  SOMA_DO_RATEIO_DIFERENTE_DO_VALOR_ESTIMADO_DO_DIC: "Soma do rateio diferente do valor estimado do DIC.",
  SOMA_VALOR_ESTIMADO_DAS_ACOES_VALOR: " Soma valor estimado das ações: {p0} ",
  SOMALI: "Somali",
  STATUS: "Status",
  STATUS_DO_PROJETO_VALOR: "Status do Projeto: {p0}",
  SUA_CONFIRMACAO_AUTORIZARA_O_INICIO_DOS_PROCEDIMENTOS_DE_CAPTACAO_DE_RECURSOS_DESTE_PROGRAMA: "Sua confirmação autorizará o início dos procedimentos de captação de recursos deste programa.",
  SUA_PERMISSAO_DE_ACESSO_AO_E_DOCS_EXPIROU_VOCE_SERA_REDIRECIONADO_PARA_O_LOGIN: "Sua permissão de acesso ao E-Docs expirou. Você será redirecionado para o login.",
  SUA_RECUSA_A_ASSINAR_ESSE_PROGRAMA_O_IMPOSSIBILITARA_DE_SER_AUTUADO: "Sua recusa a assinar esse Programa o impossibilitará de ser Autuado.",
  SUBLINHADO: "Sublinhado",
  SUCESSO: "Sucesso!",
  SUECO: "Sueco",
  SUGERIR_PROJETOS_DE_SUA_CARTEIRA_ESTRATEGICA_QUE_APRESENTEM_ALINHAMENTO_COM_O_TEMA_PROPOSTO: "Sugerir projetos de sua carteira estratégica que apresentem alinhamento com o tema proposto;",
  SUICO: "Suíço",
  SUL_COREANO_COREANO: "Sul-coreano, coreano",
  SURINAMES: "Surinamês",
  TACHADO: "Tachado",
  TAILANDES: "Tailandês",
  TAMANHO_ABAIXO_DO_LIMITE: "Tamanho abaixo do limite",
  TAMANHO_ACIMA_DO_LIMITE: "Tamanho acima do limite",
  TAMANHO_DA_FONTE: "Tamanho da fonte",
  TAMANHO_DO_CABECALHO: "Tamanho do cabeçalho",
  TAMANHO_MAXIMO: "Tamanho máximo:",
  TELEFONE: "Telefone",
  TELEFONE_COMERCIAL: "Telefone Comercial",
  TELEFONE_PESSOAL: "Telefone Pessoal",
  TER: "Ter",
  TEXTO: "×",
  TEXTO_5MB: "5mb",
  TIMORENSE_MAUBERE: "Timorense, maubere",
  TIPO: "Tipo",
  TIPO_2: "-- Tipo --",
  TIPO_DE_ORGANIZACAO: "-- Tipo de Organizacao --",
  TIPO_DE_VALOR: "Tipo de Valor",
  TITULO: "Título",
  TITULO_DO_DIC: "Titulo do DIC",
  TITULO_DO_PROGRAMA: "Titulo do Programa",
  TODAS: "Todas",
  TODO_O_ESTADO: "Todo o Estado",
  TODOS_OS_ORGAOS_DEVEM_POSSUIR_UM_PAPEL_SELECIONADO: "Todos os órgãos devem possuir um papel selecionado.",
  TORNAR_ELEGIVEL: "Tornar Elegível,",
  TORNAR_INELEGIVEL: "Tornar Inelegível,",
  TOTAL_DA_ACAO: "Total da ação",
  TOTAL_ESTIMADO_DOS_DICS_SELECIONADOS_PARA_COMPOSICAO_DO_PROGRAMA: "Total estimado dos DICs selecionados para composição do Programa.",
  TRINDADENSE: "Trindadense",
  TURCO: "Turco",
  UCRANIANO: "Ucraniano",
  UGANDENSE: "Ugandense",
  ULTIMO: "Último",
  UNIDADE_DE_MEDIDA: "UNIDADE DE MEDIDA",
  UNIDADE_DE_MEDIDA_2: "UNIDADE DE MEDIDA:",
  UNIDADE_ORCAMENTARIA: "Unidade Orçamentária",
  UNIDADE_ORCAMENTARIA_2: "Unidade orçamentária",
  UO: "UO",
  URUGUAIO: "Uruguaio",
  UTILIZE_OS_FILTROS_ACIMA_PARA_ADICIONAR_AS_ACOES_DO_PLANEJAMENTO_AO_PROJETO: "Utilize os filtros acima para adicionar as ações do planejamento ao projeto.",
  UTILIZE_OS_FILTROS_ACIMA_PARA_CARREGAR_A_LISTA_DE_ACOES_ANO_E_UO_SAO_OBRIGATORIOS: "Utilize os filtros acima para carregar a lista de ações (Ano e UO são obrigatórios).",
  VALOR_10_000_CARACTERES: " {p0}/10.000 caracteres ",
  VALOR_2: "Valor",
  VALOR_ESTIMADO: "Valor Estimado:",
  VALOR_ESTIMADO_2: "Valor Estimado",
  VALOR_ESTIMADO_DO_PROJETO_INCOMPATIVEL_COM_SOMATORIO_DE_VALORES_INFORMADO_NAS_ACOES: "Valor estimado do projeto incompativel com somatorio de valores informado nas ações.",
  VALOR_ESTIMADO_TOTAL: "Valor Estimado Total",
  VALOR_INFERIOR_AO_LIMITE: "Valor inferior ao limite",
  VALOR_LOA_VALOR: " Valor LOA {p0} ",
  VALOR_PPA_VALOR: " Valor PPA {p0} ",
  VALOR_SELECIONADAS: " {p0} selecionadas ",
  VALOR_SELECIONADOS: " {p0} selecionados ",
  VALOR_SUPERIOR_AO_LIMITE: "Valor superior ao limite",
  VALOR_TOTAL_ESTIMADO: "Valor Total Estimado",
  VALOR_VALOR_2: "{p0} - {p1}",
  VENEZUELANO: "Venezuelano",
  VERIFICAR_A_CONFORMIDADE_COM_A_LOA_LDO_E_PPA: "Verificar a conformidade com a LOA, LDO e PPA;",
  VERIFIQUE_OS_ITENS_OBRIGATORIOS_ANTES_DE_ENVIAR_O_PROJETO_PARA_ANALISE: "Verifique os itens obrigatórios antes de enviar o projeto para análise.",
  VERIFIQUE_SE_JA_FAZ_PARTE_DA_EQUIPE: "Verifique se já faz parte da equipe.",
  VERIFIQUE_SE_O_PROJETO_ESTA_VALIDO: "Verifique se o projeto está válido.",
  VERIFIQUE_SUA_CONEXAO_COM_A_INTERNET: "Verifique sua conexão com a internet.",
  VIDEO: "Vídeo",
  VIETNAMITA: "Vietnamita",
  VINCULAR_O_DIC_A_ESTE_PROGRAMA_IRA_DESVINCULA_LO_DO_PROGRAMA_ACIMA: "Vincular o DIC à este Programa irá desvinculá-lo do Programa acima!",
  VISUALIZACAO: "Visualização",
  VISUALIZAR: "Visualizar",
  VISUALIZAR_CARTA_CONSULTA: "Visualizar Carta Consulta",
  VISUALIZAR_PESQUISA_DE_FONTE_DE_FINANCIAMENTO: "Visualizar Pesquisa de Fonte de Financiamento",
  VISUALIZAR_PROSPECCAO: "Visualizar Prospecção",
  VOCE_ESTA_PRESTES_A_DELETAR_O_SEGUINTE_REGISTRO: "Você está prestes a deletar o seguinte registro:",
  VOLTAR: "Voltar",
  ZIMBABUENSE: "Zimbabuense",
  A_SIGLA_INFORMADA_JA_ESTA_EM_USO_POR_OUTRO_DIC: "A sigla informada já está em uso por outro DIC.",
  STATUS_DO_PROJETO_VALOR_2: "Status do projeto: {p0}",
  NOVO_STATUS_2: "Novo status",
  SALVAR_E_ENVIAR_2: "Salvar e enviar",
  PEDIR_PARECER_2: "Pedir parecer",
  ASSINAR_E_AUTUAR_2: "Assinar e autuar",
  ESTA_ACAO_REALIZARA_NO_E_DOCS_A_ASSINATURA_DO_DIC_E_A_AUTUACAO_DO_PROCESSO_DE_ELEGIBILIDADE_DO_PROJETO_UTILIZA_2: " Esta ação realizará no E-Docs a assinatura do DIC e a autuação do processo de elegibilidade do projeto, utilizando a sua identidade - {p0} ({p1}). ",
  AUTUACAO_DE_PROCESSO_DE_SOLICITACAO_DE_CAPTACAO_DE_RECURSOS_PARA_A_SUA_INSTITUICAO_2: "Autuação de processo de solicitação de captação de recursos para a sua instituição;",
  PROCESSO_AUTUADO_E_ENCAMINHADO_COM_SUCESSO_2: "Processo autuado e encaminhado com sucesso!",
  MOTIVO_DO_ARQUIVAMENTO: "Motivo do arquivamento",
  PDF_ASSINATURA_E_CAPTURA_FINALIZADOS_COM_SUCESSO: "PDF, assinatura e captura finalizados com sucesso!",
  TORNAR_ELEGIVEL_2: "Tornar elegível,",
  ASSINAR_E_CAPTURAR_PARECER_2: "Assinar e capturar parecer",
  TORNAR_INELEGIVEL_2: "Tornar inelegível,",
  ENTRANHAR_PARECERES_2: "Entranhar pareceres",
  ENTRANHAMENTO_DOS_PARECERES_FINALIZADO_COM_SUCESSO: "Entranhamento dos pareceres finalizado com sucesso!",
  FECHAR_MODAL: "Fechar modal",
  DISTRIBUICAO_LINEAR: "Distribuição linear",
  O_DIC_SELECIONADO_JA_ESTA_VINCULADO_AO_SEGUINTE_PROGRAMA_2: "O DIC selecionado já está vinculado ao seguinte programa:",
  VINCULAR_O_DIC_A_ESTE_PROGRAMA_IRA_DESVINCULA_LO_DO_PROGRAMA_ACIMA_2: "Vincular o DIC a este programa irá desvinculá-lo do programa acima!",
  AUTUAR_PROGRAMA: "Autuar Programa",
  ENTRANHAR_PROGRAMA: "Entranhar Programa",
  ENCERRAR_PROCESSO: "Encerrar Processo",
  NAO_AUTORIZO_2: "Não autorizo",
  SOLICITAR_AUTORIZACAO_2: "Solicitar autorização",
  PROGRAMA_AUTUADO_E_ENTRANHADO_COM_SUCESSO: "Programa autuado e entranhado com sucesso!",
  OCORREU_UM_ERRO_AO_AUTUAR_OU_ENTRANHAR_O_PROGRAMA_NO_E_DOCS: "Ocorreu um erro ao autuar ou entranhar o Programa no E-Docs!",
  GERACAO_DO_PDF: "Geração do PDF",
  ENTRANHAMENTO_DO_PARECER: "Entranhamento do parecer",
  ENCERRAMENTO_DO_PROCESSO: "Encerramento do processo",
  NAO_FOI_POSSIVEL_INICIAR_A_AUTUACAO_NO_E_DOCS: "Não foi possível iniciar a autuação no E-Docs.",
  ASSINATURA_E_CAPTURA_DO_PARECER_INICIADAS_NO_E_DOCS: "Assinatura e captura do parecer iniciadas no E-Docs.",
  ERRO_AO_INICIAR_A_ASSINATURA_E_CAPTURA_DO_PARECER_NO_E_DOCS: "Erro ao iniciar a assinatura e captura do parecer no E-Docs.",
} as const;

export const MENSAGENS: Readonly<Record<keyof typeof MENSAGENS_PT_BR, string>> = Object.freeze(MENSAGENS_PT_BR);

export type ChaveMensagem = keyof typeof MENSAGENS;

/** Substitui parâmetros sem interpretar HTML nem processar novamente seus valores. */
export function formatarMensagem(
  mensagem: string,
  parametros: Readonly<Record<string, unknown>>,
): string {
  return mensagem.replace(/\{(\w+)\}/g, (original, chave: string) =>
    Object.prototype.hasOwnProperty.call(parametros, chave)
      ? String(parametros[chave] ?? '')
      : original,
  );
}

/**
 * Arquivo contendo constantes reutilizadas em toda a aplicação
 */

/**
 * Lista de caminhos a serem ignorados na geração de breadcrumbs.
 *
 * Utilizado em `src/app/core/components/breadcrumb/breadcrumb.component.ts`
 */
export const BREADCRUMB_LISTA_CAMINHOS_EXCLUSAO: Array<string> = [
  '',
  'main',
  'login',
];

/**
 * Lista de caminhos "principais" da aplicação.
 *
 * Utilizado em `src/app/core/components/breadcrumb/breadcrumb.component.ts`
 */
export const BREADCRUMB_LISTA_CAMINHOS_PRINCIPAIS: Array<string> = [
  'home',
  'projetos',
  'programas',
  'pessoas',
  'organizacoes',
  'cartasconsulta',
  'prospeccao',
];

export const BREADCRUMB_LISTA_CAMINHOS_FILHOS: Array<string> = [
  'criar',
  'editar',
  'editar/'
];

export const BREADCRUMB_LISTA_CAMINHOS_ESPECIFICOS: Array<{
  caminho: string;
  contexto: string;
}> = [
  { caminho: 'meu-perfil', contexto: 'pessoas' },
  { caminho: 'visualizar', contexto: 'cartasconsulta' },
  { caminho: 'visualizar', contexto: 'prospeccao' },
  { caminho: 'assinaturas', contexto: 'programas' },
];

export const BREADCRUMB_COLECAO_CAMINHO_TITULO: Record<string, string> = {
  home: MENSAGENS.PAGINA_PRINCIPAL,

  projetos: MENSAGENS.DOCUMENTO_INICIAL_DE_CAPTACAO_DIC,
  projetoscriar: MENSAGENS.NOVO_DIC_DOCUMENTO_INICIAL_DE_CAPTACAO,
  projetoseditar: MENSAGENS.EDITAR_DOCUMENTO_INICIAL_DE_CAPTACAO_DIC,
  projetosparecer: MENSAGENS.PARECER,

  pessoas: MENSAGENS.PESSOAS,
  pessoascriar: MENSAGENS.NOVA_PESSOA,
  pessoaseditar: MENSAGENS.EDITAR_PESSOA,
  pessoasmeuperfil: MENSAGENS.MEU_PERFIL, // Caso específico

  organizacoes: MENSAGENS.ORGANIZACOES,
  organizacoescriar: MENSAGENS.NOVA_ORGANIZACAO,
  organizacoeseditar: MENSAGENS.EDITAR_ORGANIZACAO,

  programas: MENSAGENS.PROGRAMAS,
  programascriar: MENSAGENS.NOVO_PROGRAMA,
  programaseditar: MENSAGENS.EDITAR_PROGRAMA,
  programasassinaturas: MENSAGENS.AUTORIZACOES_DO_PROGRAMA,

  cartasconsulta: MENSAGENS.PESQUISA_DE_FONTES_DE_FINANCIAMENTO,
  cartasconsultacriar: MENSAGENS.NOVA_PESQUISA_DE_FONTE_DE_FINANCIAMENTO,
  cartasconsultaeditar: MENSAGENS.EDITAR_PESQUISA_DE_FONTE_DE_FINANCIAMENTO,
  cartasconsultavisualizar: MENSAGENS.VISUALIZAR_PESQUISA_DE_FONTE_DE_FINANCIAMENTO, // Caso específico

  prospeccao: MENSAGENS.PROSPECCAO,
  prospeccaocriar: MENSAGENS.NOVA_PROSPECCAO,
  prospeccaoeditar: MENSAGENS.EDITAR_PROSPECCAO,
  prospeccaovisualizar: MENSAGENS.VISUALIZAR_PROSPECCAO, // Caso específico

};

/**
 * Lista de nacionalidades, com o propósito de alimentar opções
 * de um elemento HTML `<select>` ou similar.
 *
 * Utilizado no componente de formulário de pessoas (`PessoaFormComponent`).
 */
export const LISTA_NACIONALIDADES: Array<string> = [
  MENSAGENS.ANTIGUANO,
  MENSAGENS.ARGENTINO,
  MENSAGENS.BAHAMENSE,
  MENSAGENS.BARBADIANO_BARBADENSE,
  MENSAGENS.BELIZENHO,
  MENSAGENS.BOLIVIANO,
  MENSAGENS.BRASILEIRO,
  MENSAGENS.CHILENO,
  MENSAGENS.COLOMBIANO,
  MENSAGENS.COSTARRIQUENHO,
  MENSAGENS.CUBANO,
  MENSAGENS.DOMINICANO,
  MENSAGENS.EQUATORIANO,
  MENSAGENS.SALVADORENHO,
  MENSAGENS.GRANADINO,
  MENSAGENS.GUATEMALTECO,
  MENSAGENS.GUIANES,
  MENSAGENS.GUIANENSE,
  MENSAGENS.HAITIANO,
  MENSAGENS.HONDURENHO,
  MENSAGENS.JAMAICANO,
  MENSAGENS.MEXICANO,
  MENSAGENS.NICARAGUENSE,
  MENSAGENS.PANAMENHO,
  MENSAGENS.PARAGUAIO,
  MENSAGENS.PERUANO,
  MENSAGENS.PORTORRIQUENHO,
  MENSAGENS.DOMINICANA,
  'São-cristovense',
  'São-vicentino',
  'Santa-lucense',
  MENSAGENS.SURINAMES,
  MENSAGENS.TRINDADENSE,
  MENSAGENS.URUGUAIO,
  MENSAGENS.VENEZUELANO,
  MENSAGENS.ALEMAO,
  MENSAGENS.AUSTRIACO,
  MENSAGENS.BELGA,
  MENSAGENS.CROATA,
  MENSAGENS.DINAMARQUES,
  MENSAGENS.ESLOVACO,
  MENSAGENS.ESLOVENO,
  MENSAGENS.ESPANHOL,
  MENSAGENS.FRANCES,
  MENSAGENS.GREGO,
  MENSAGENS.HUNGARO,
  MENSAGENS.IRLANDES,
  MENSAGENS.ITALIANO,
  MENSAGENS.NORUEGO,
  MENSAGENS.HOLANDES,
  MENSAGENS.POLONES,
  MENSAGENS.PORTUGUES,
  MENSAGENS.BRITANICO,
  MENSAGENS.INGLES,
  MENSAGENS.GALES,
  MENSAGENS.ESCOCES,
  MENSAGENS.ROMENO,
  MENSAGENS.RUSSO,
  MENSAGENS.SERVIO,
  MENSAGENS.SUECO,
  MENSAGENS.SUICO,
  MENSAGENS.TURCO,
  MENSAGENS.UCRANIANO,
  MENSAGENS.AMERICANO,
  MENSAGENS.CANADENSE,
  MENSAGENS.ANGOLANO,
  MENSAGENS.MOCAMBICANO,
  'Sul-africano',
  MENSAGENS.ZIMBABUENSE,
  MENSAGENS.ARGELIA,
  MENSAGENS.COMORENSE,
  MENSAGENS.EGIPCIO,
  MENSAGENS.LIBIO,
  MENSAGENS.MARROQUINO,
  MENSAGENS.GANES,
  MENSAGENS.QUENIANO,
  MENSAGENS.RUANDES,
  MENSAGENS.UGANDENSE,
  MENSAGENS.BECHUANO,
  MENSAGENS.MARFINENSE,
  MENSAGENS.CAMARONENSE,
  MENSAGENS.NIGERIANO,
  MENSAGENS.SOMALI,
  MENSAGENS.AUSTRALIANO,
  MENSAGENS.NEOZELANDES,
  MENSAGENS.AFEGAO,
  MENSAGENS.SAUDITA,
  MENSAGENS.ARMENO,
  MENSAGENS.BANGLADESH,
  MENSAGENS.CHINES,
  MENSAGENS.NORTE_COREANO_COREANO,
  MENSAGENS.SUL_COREANO_COREANO,
  MENSAGENS.INDIANO,
  MENSAGENS.INDONESIO,
  MENSAGENS.IRAQUIANO,
  MENSAGENS.IRANIANO,
  MENSAGENS.ISRAELITA,
  MENSAGENS.JAPONES,
  MENSAGENS.MALAIO,
  MENSAGENS.NEPALES,
  MENSAGENS.OMANENSE,
  MENSAGENS.PAQUISTANES,
  MENSAGENS.PALESTINO,
  MENSAGENS.QATARENSE,
  MENSAGENS.SIRIO,
  MENSAGENS.CINGALES,
  MENSAGENS.TAILANDES,
  MENSAGENS.TIMORENSE_MAUBERE,
  MENSAGENS.ARABE_EMIRATENSE,
  MENSAGENS.VIETNAMITA,
  MENSAGENS.IEMENITA,
];

/**
 * Lista de gêneros, com o propósito de alimentar opções
 * de um elemento HTML `<select>` ou similar.
 *
 * Utilizado no componente de formulário de pessoas (`PessoaFormComponent`).
 */
export const LISTA_GENEROS: Array<string> = [MENSAGENS.MASCULINO, MENSAGENS.FEMININO, MENSAGENS.OUTRO];

/**
 * Tempo de espera (em milisegundos) de ociosidade por parte do usuário
 * para começar a emitir eventos.
 *
 * Utilizado primariamente em funções de espera como `setTimeout`
 * e operadores Rxjs `debounceTime` , `auditTime`, `throttleTime`, etc.
 */
export const TEMPO_INPUT_USUARIO: number = 750;

/**
 * Tempo de espera reduzido para validar a disponibilidade da sigla do DIC.
 */
export const TEMPO_VALIDACAO_SIGLA: number = 300;

/**
 * Tempo de espera (em milisegundos) para recálculo de valores.
 * Dependente de `TEMPO_INPUT_USUARIO` a fim de evitar conflito
 * entre dados novos (após o input do usuário) e antigos.
 */
export const TEMPO_RECALCULO: number = TEMPO_INPUT_USUARIO + 50;

const ERRO_MENSAGEM_REQUIRED: string = MENSAGENS.CAMPO_OBRIGATORIO;
const ERRO_MENSAGEM_EMAIL: string = MENSAGENS.EMAIL_INVALIDO;
const ERRO_MENSAGEM_MAXLENGTH: string = MENSAGENS.TAMANHO_ACIMA_DO_LIMITE;
const ERRO_MENSAGEM_MINLENGTH: string = MENSAGENS.TAMANHO_ABAIXO_DO_LIMITE;
const ERRO_MENSAGEM_MAX: string = MENSAGENS.VALOR_SUPERIOR_AO_LIMITE;
const ERRO_MENSAGEM_MIN: string = MENSAGENS.VALOR_INFERIOR_AO_LIMITE;
const ERRO_MENSAGEM_CPF: string = MENSAGENS.CPF_INVALIDO;
const ERRO_MENSAGEM_MEMBRO_EQUIPE_SEM_PAPEL: string =
  MENSAGENS.ALGUM_MEMBRO_DA_EQUIPE_NAO_POSSUI_UM_PAPEL_ATRIBUIDO;
const ERRO_MENSAGEM_LIMITE_RATEIO: string =
  MENSAGENS.SOMA_DO_RATEIO_DIFERENTE_DO_VALOR_ESTIMADO_DO_DIC;
const ERRO_MENSAGEM_EQUIPE_SEM_MEMBRO_ATIVO: string = MENSAGENS.EQUIPE_ELABORACAO_DEVE_CONTER_PELO_MENOS_UM_MEMBRO;
const ERRO_MENSAGEM_PROGRAMA_SEM_ORGAO_GESTOR: string = MENSAGENS.PROGRAMA_DEVE_CONTER_AO_MENOS_UM_ORGAO_GESTOR;
const ERRO_MENSAGEM_PROGRAMA_ORGAO_SEM_PAPEL: string = MENSAGENS.TODOS_OS_ORGAOS_DEVEM_POSSUIR_UM_PAPEL_SELECIONADO;

/**
 * Objeto de coleção de mensagens padrão de erro para validações de formulários.
 *
 * Utilizado em src/app/core/templates/validation-message/validation-message.component.ts
 */
export const COLECAO_ERRO_MENSAGEM: Record<string, string> = {
  required: ERRO_MENSAGEM_REQUIRED,
  email: ERRO_MENSAGEM_EMAIL,
  maxlength: ERRO_MENSAGEM_MAXLENGTH,
  minlength: ERRO_MENSAGEM_MINLENGTH,
  max: ERRO_MENSAGEM_MAX,
  min: ERRO_MENSAGEM_MIN,
  cpf: ERRO_MENSAGEM_CPF,
  membroEquipeSemPapel: ERRO_MENSAGEM_MEMBRO_EQUIPE_SEM_PAPEL,
  limiteRateio: ERRO_MENSAGEM_LIMITE_RATEIO,
  equipeSemMembroAtivo: ERRO_MENSAGEM_EQUIPE_SEM_MEMBRO_ATIVO,
  precisaAoMenosUmOrgaoGestor: ERRO_MENSAGEM_PROGRAMA_SEM_ORGAO_GESTOR,
  orgaoPrecisaTerUmPapel: ERRO_MENSAGEM_PROGRAMA_ORGAO_SEM_PAPEL,
};

/**
 * Objeto de coleção de mensagens de tooltip do formulário de projeto.
 *
 * Utilizado para alimentar propriedade de input `texto` de
 * um componente <form-helper-tooltip>.
 */
export const COLECAO_TEXTO_TOOLTIP_FORMULARIO_PROJETO: Record<string, string> =
  {
    sigla: MENSAGENS.INDICAR_O_NOME_FANTASIA_DO_DIC,
    titulo:
      MENSAGENS.INFORMAR_O_NOME_DO_DIC_O_NOME_DEVERA_REFLETIR_O_OBJETIVO_MAIOR_DO_DIC,
    idOrganizacao:
      MENSAGENS.IDENTIFIQUE_A_INSTITUICAO_SECRETARIA_DE_ESTADO_AUTARQUIA_ORGAO_DE_OUTROS_PODERES_DO_ESTADO_ETC_QUE_SERA_O_TOMA,
    valorEstimado:
      MENSAGENS.INDICAR_O_VALOR_TOTAL_NECESSARIO_PARA_A_EXECUCAO_DO_DIC_PROPOSTO_EM_R,
    idMicrorregioesList:
      MENSAGENS.I_INFORMAR_AS_INSTITUICOES_ENVOLVIDAS_NA_IMPLEMENTACAO_DO_PROJETO_E_SUAS_RESPECTIVAS_RESPONSABILIDADES_NA_EXEC,
    objetivo:
      MENSAGENS.DEVERA_REFLETIR_O_QUE_SE_DESEJA_ALCANCAR_COM_AS_ACOES_DO_DIC_ABRANGENDO_A_VISAO_AMPLA_E_O_SEU_PROPOSITO_GERAL,
    objetivoEspecifico:
      MENSAGENS.DEVERAO_CORRESPONDER_AOS_RESULTADOS_QUE_O_DIC_PRETENDE_ATINGIR_CONTRIBUINDO_PARA_O_ALCANCE_DO_OBJETIVO_GERAL_D,
    situacaoProblema:
      MENSAGENS.IDENTIFICAR_O_S_PROBLEMA_S_QUE_AS_ACOES_DO_DIC_CANDIDATO_A_FINANCIAMENTO_SE_PROPOEM_SOLUCIONAR_OU_MINORAR_DESC,
    solucoesPropostas:
      MENSAGENS.DESCREVER_AS_ACOES_ESCOLHIDAS_PARA_O_ENFRENTAMENTO_OU_SOLUCAO_DO_S_PROBLEMA_S_DESCRITO_S_NO_ITEM_ANTERIOR,
    impactos:
      MENSAGENS.INFORMAR_I_AS_MEDIDAS_DE_SUSTENTABILIDADE_A_SEREM_ADOTADAS_E_OS_CUSTOS_ADICIONAIS_ESTIMADOS_DECORRENTES_DA_IMP,
    arranjosInstitucionais:
      MENSAGENS.I_INFORMAR_O_ORGAO_EXECUTOR_PRINCIPAL_DO_PROGRAMA_OU_DIC_E_DEMAIS_ORGAOS_PARTICIPANTES_SE_EXISTENTES_II_INFORM,
    nomeIndicador:
      MENSAGENS.PREFERENCIALMENTE_DEVERAO_SER_CONSIDERADOS_OS_INDICADORES_CHAVE_NACIONAIS_CONSTANTES_DO_PLANO_PLURIANUAL_2024,
    descricaoIndicador:
      MENSAGENS.DESCREVER_CADA_INDICADOR_DE_FORMA_ESPECIFICA_E_ESTABELECER_AS_FORMULAS_DE_CALCULO_ADEQUADAS_FAZER_REFERENCIA_A,
    descricaoMeta:
      MENSAGENS.APONTAR_O_RESULTADO_ESPECIFICO_E_DETERMINADO_A_SER_ALCANCADO_CUJA_IMPLEMENTACAO_SERA_MEDIDA_POR_MEIO_DO_INDICA,
    idResponsavelProponente: MENSAGENS.PESSOA_QUE_RESPONDE_PELO_ORGAO_DE_ORIGEM,
    equipeElaboracao: MENSAGENS.PESSOAS_RESPONSAVEIS_PELA_ELABORACAO_DO_DIC,
    descricaoAcaoPrincipal: MENSAGENS.INSERIR_O_NOME_DA_ACAO,
    valorEstimadoAcaoPrincipal: MENSAGENS.PREENCHER_O_VALOR_ESTIMADO_TOTAL_A_SER_DESTINADO_A_IMPLANTACAO_DAS_ACOES_PRINCIPAIS_O_VALOR_DEVERA_SER_COMPATI,
    descricaoAcoesSecudariasProdutos: MENSAGENS.INSERIR_AS_ACOES_SECUNDARIAS_SE_HOUVER_E_OS_PRODUTOS_OS_PRODUTOS_DEVERAO_COMPREENDER_OS_BENS_OU_SERVICOS_OFERE,
    pecasPlanejamento: MENSAGENS.I_APONTAR_QUAIS_AREAS_ESTRATEGICAS_REFERIDAS_NO_PLANEJAMENTO_ESTRATEGICO_SAO_ATENDIDAS_PELO_DIC_APONTAR_SE_O_P,
    tipoIndicadorDescricao: MENSAGENS.DESCREVER_O_TIPO_DE_INDICADOR,
    valorTotalEstimadoPrograma: MENSAGENS.TOTAL_ESTIMADO_DOS_DICS_SELECIONADOS_PARA_COMPOSICAO_DO_PROGRAMA,
    dicelegivel: MENSAGENS.LISTA_DE_DICS_ELEGIVEIS_PARA_VINCULACAO_A_UM_PROGRAMA
  };
